# Generated by Django 4.2.8 on 2023-12-07 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter your email address.", max_length=254
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Enter your name.", max_length=255),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Enter the content of your contact request."
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time of the contact request.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the title of the article.", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="A URL-friendly version of the title, automatically generated from the title.",
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Enter the content of the article."),
                ),
                (
                    "publication_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the article was published.",
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        default=True,
                        help_text="Check to make the article available online; uncheck to take it offline.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Select the author of the article.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
